module.exports = {
  Agent: require('./Agent'),
  Driver: require('./Driver'),
  Vehicle: require('./Vehicle'),
  Order: require('./Order'),
  DeliveryJob: require('./DeliveryJob'),
  DeliveryEvent: require('./DeliveryEvent'),
  TrackingHistory: require('./TrackingHistory'),
  Notification: require('./Notification'),
  SyncJob: require('./SyncJob'),
  SyncLog: require('./SyncLog'),
  Farmer: require('./Farmer'),
  Buyer: require('./Buyer'),
  Employee: require('./Employee'),
  Product: require('./Product'),
  InventoryHistory: require('./InventoryHistory'),
  Payment: require('./Payment'),
  Commission: require('./Commission'),
  FarmerSettlement: require('./FarmerSettlement'),
  Pickup: require('./Pickup'),
  Counter: require('./Counter'),
};
